version: "3.8"

services:
  web:
    build: .
    restart: always
    network_mode: "host"
    volumes:
      # Bind mounts для мгновенного обновления без пересборки
      - ./templates:/app/templates
      - ./static:/app/static
      - ./media:/app/media
      - ./logs:/app/logs
      - ./api:/app/api
      - ./app:/app/app
      - ./core:/app/core
      - ./services:/app/services
      - ./models:/app/models
      # Только для файлов, которые часто меняются в разработке
    environment:
      - DATABASE_URL=mysql+pymysql://wazir:c:ICx9Pr{48y>6BmBc3r@127.0.0.1/wazir
      - SECRET_KEY=CdKxf8AKid3xI9QIPgJUGzgJFsDRXaBW1AcmZUvcP8llHN6Bmr5jWP
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - BACKEND_CORS_ORIGINS=["*"]
      - PYTHON_ENV=development
      # Включаем автоперезагрузку в режиме разработки
    command: uvicorn asgi:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app 