"""add_views_field_to_properties

Revision ID: 449e5825a758
Revises: 77727a9fb889
Create Date: 2025-06-11 01:55:29.953099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '449e5825a758'
down_revision = '77727a9fb889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('views', sa.Integer(), nullable=False))
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Enum('ADMIN', 'USER', 'MANAGER', 'COMPANY', name='userrole'),
               nullable=True)
    op.alter_column('users', 'company_logo_url',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('users', 'company_address',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'company_address',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.alter_column('users', 'company_logo_url',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'USER', 'MANAGER', 'COMPANY', name='userrole'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=False)
    op.drop_column('properties', 'views')
    # ### end Alembic commands ### 