"""Add panorama tables for properties and service cards

Revision ID: 58bc1382d90f
Revises: f525ae18328f
Create Date: 2025-07-15 22:33:03.522794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58bc1382d90f'
down_revision = 'f525ae18328f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Создаем новые таблицы панорам
    op.create_table('property_panoramas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('file_id', sa.String(length=100), nullable=True),
    sa.Column('original_url', sa.String(length=255), nullable=True),
    sa.Column('optimized_url', sa.String(length=255), nullable=True),
    sa.Column('preview_url', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_panoramas_id'), 'property_panoramas', ['id'], unique=False)
    
    op.create_table('service_card_panoramas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_card_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('file_id', sa.String(length=100), nullable=True),
    sa.Column('original_url', sa.String(length=255), nullable=True),
    sa.Column('optimized_url', sa.String(length=255), nullable=True),
    sa.Column('preview_url', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_card_id'], ['service_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_card_panoramas_id'), 'service_card_panoramas', ['id'], unique=False)
    
    # Обновляем properties - удаляем старые поля панорам
    try:
        op.drop_index('idx_properties_coordinates', table_name='properties')
    except:
        pass
    try:
        op.drop_index('ix_properties_media_id', table_name='properties')
    except:
        pass
    
    # Удаляем старые поля панорам из properties
    columns_to_drop = [
        'tour_360_uploaded_at', 'tour_360_original_url', 'tour_360_thumbnail_url',
        'tour_360_optimized_url', 'tour_360_metadata', 'tour_360_preview_url',
        'tour_360_file_id', 'tour_360_url'
    ]
    
    for column in columns_to_drop:
        try:
            op.drop_column('properties', column)
        except:
            pass
    
    # Обновляем service_card_images - сначала удаляем foreign key, потом индексы
    try:
        op.drop_constraint('service_card_images_ibfk_1', 'service_card_images', type_='foreignkey')
    except:
        pass
    
    # Удаляем индексы
    indexes_to_drop = [
        'idx_service_card_images_card', 'idx_service_card_images_card_id',
        'idx_service_card_images_id', 'idx_service_card_images_main'
    ]
    
    for index in indexes_to_drop:
        try:
            op.drop_index(index, table_name='service_card_images')
        except:
            pass
    
    # Создаем новый индекс и foreign key
    op.create_index(op.f('ix_service_card_images_id'), 'service_card_images', ['id'], unique=False)
    op.create_foreign_key(None, 'service_card_images', 'service_cards', ['service_card_id'], ['id'])
    
    # Обновляем service_cards - удаляем foreign key, индексы, потом старые поля
    try:
        op.drop_constraint('service_cards_ibfk_1', 'service_cards', type_='foreignkey')
    except:
        pass
    
    # Удаляем индексы service_cards
    service_indexes_to_drop = [
        'idx_service_cards_360_file_id', 'idx_service_cards_360_uploaded',
        'idx_service_cards_category', 'idx_service_cards_category_id',
        'idx_service_cards_id', 'idx_service_cards_is_active',
        'idx_service_cards_photos_uploaded'
    ]
    
    for index in service_indexes_to_drop:
        try:
            op.drop_index(index, table_name='service_cards')
        except:
            pass
    
    # Создаем новые индексы и foreign key для service_cards
    op.create_index(op.f('ix_service_cards_id'), 'service_cards', ['id'], unique=False)
    op.create_foreign_key(None, 'service_cards', 'service_categories', ['category_id'], ['id'])
    
    # Удаляем старые поля панорам из service_cards
    service_columns_to_drop = [
        'tour_360_uploaded_at', 'tour_360_thumbnail_url', 'tour_360_original_url',
        'tour_360_optimized_url', 'tour_360_metadata', 'tour_360_preview_url',
        'tour_360_file_id', 'tour_360_url'
    ]
    
    for column in service_columns_to_drop:
        try:
            op.drop_column('service_cards', column)
        except:
            pass
    
    # Обновляем service_categories - удаляем индексы
    category_indexes_to_drop = [
        'idx_service_categories_id', 'idx_service_categories_is_active',
        'idx_service_categories_slug', 'slug'
    ]
    
    for index in category_indexes_to_drop:
        try:
            op.drop_index(index, table_name='service_categories')
        except:
            pass
    
    # Создаем новые индексы для service_categories
    op.create_index(op.f('ix_service_categories_id'), 'service_categories', ['id'], unique=False)
    op.create_index(op.f('ix_service_categories_slug'), 'service_categories', ['slug'], unique=True)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_categories_slug'), table_name='service_categories')
    op.drop_index(op.f('ix_service_categories_id'), table_name='service_categories')
    op.create_index('slug', 'service_categories', ['slug'], unique=True)
    op.create_index('idx_service_categories_slug', 'service_categories', ['slug'], unique=False)
    op.create_index('idx_service_categories_is_active', 'service_categories', ['is_active'], unique=False)
    op.create_index('idx_service_categories_id', 'service_categories', ['id'], unique=False)
    
    # Восстанавливаем старые поля service_cards
    op.add_column('service_cards', sa.Column('tour_360_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('service_cards', sa.Column('tour_360_file_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.add_column('service_cards', sa.Column('tour_360_preview_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('service_cards', sa.Column('tour_360_metadata', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('service_cards', sa.Column('tour_360_optimized_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('service_cards', sa.Column('tour_360_original_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('service_cards', sa.Column('tour_360_thumbnail_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('service_cards', sa.Column('tour_360_uploaded_at', mysql.DATETIME(), nullable=True))
    
    op.drop_constraint(None, 'service_cards', type_='foreignkey')
    op.create_foreign_key('service_cards_ibfk_1', 'service_cards', 'service_categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_service_cards_id'), table_name='service_cards')
    
    # Восстанавливаем старые поля properties
    op.add_column('properties', sa.Column('tour_360_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('properties', sa.Column('tour_360_file_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.add_column('properties', sa.Column('tour_360_preview_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('properties', sa.Column('tour_360_metadata', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('properties', sa.Column('tour_360_optimized_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('properties', sa.Column('tour_360_thumbnail_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('properties', sa.Column('tour_360_original_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('properties', sa.Column('tour_360_uploaded_at', mysql.DATETIME(), nullable=True))
    
    op.drop_index(op.f('ix_service_card_panoramas_id'), table_name='service_card_panoramas')
    op.drop_table('service_card_panoramas')
    op.drop_index(op.f('ix_property_panoramas_id'), table_name='property_panoramas')
    op.drop_table('property_panoramas')
    # ### end Alembic commands ###