"""Add chat_id to SupportTicket

Revision ID: 58e5034ec77f
Revises: df556b73f817
Create Date: 2025-05-24 14:53:08.436371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58e5034ec77f'
down_revision = 'df556b73f817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('chat_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_tickets', 'chat_id')
    # ### end Alembic commands ### 