"""Add updated_at to chat_messages

Revision ID: 9a7c0b9990d1
Revises: 58e5034ec77f
Create Date: 2025-05-24 15:00:22.584957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7c0b9990d1'
down_revision = '58e5034ec77f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'updated_at')
    # ### end Alembic commands ### 