"""add amenities fields to properties

Revision ID: d7e8f9a01234
Revises: 9a7c0b9990d1
Create Date: 2024-12-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e8f9a01234'
down_revision = '9a7c0b9990d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем новые поля удобств в таблицу properties
    op.add_column('properties', sa.Column('has_elevator', sa.Boolean(), nullable=True, default=False))
    op.add_column('properties', sa.Column('has_security', sa.Boolean(), nullable=True, default=False))
    op.add_column('properties', sa.Column('has_internet', sa.Boolean(), nullable=True, default=False))
    op.add_column('properties', sa.Column('has_air_conditioning', sa.Boolean(), nullable=True, default=False))
    op.add_column('properties', sa.Column('has_heating', sa.Boolean(), nullable=True, default=False))
    op.add_column('properties', sa.Column('has_yard', sa.Boolean(), nullable=True, default=False))
    op.add_column('properties', sa.Column('has_pool', sa.Boolean(), nullable=True, default=False))
    op.add_column('properties', sa.Column('has_gym', sa.Boolean(), nullable=True, default=False))
    op.add_column('properties', sa.Column('bathroom_type', sa.String(50), nullable=True))
    op.add_column('properties', sa.Column('category_id', sa.Integer(), nullable=True))
    
    # Добавляем внешний ключ для category_id
    op.create_foreign_key('fk_properties_category_id', 'properties', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем внешний ключ
    op.drop_constraint('fk_properties_category_id', 'properties', type_='foreignkey')
    
    # Удаляем добавленные столбцы
    op.drop_column('properties', 'category_id')
    op.drop_column('properties', 'bathroom_type')
    op.drop_column('properties', 'has_gym')
    op.drop_column('properties', 'has_pool')
    op.drop_column('properties', 'has_yard')
    op.drop_column('properties', 'has_heating')
    op.drop_column('properties', 'has_air_conditioning')
    op.drop_column('properties', 'has_internet')
    op.drop_column('properties', 'has_security')
    op.drop_column('properties', 'has_elevator')
    # ### end Alembic commands ### 